### ISSUE TITLE
java.nio.BufferOverflowException in com.spotify.helios.testing.LoggingLogStreamFollower

### ISSUE THREAD

**Issue by mattnworb** [spotify/helios#1078]
```
08:00:33.224 [HeliosSoloLogService] WARN  c.s.h.testing.HeliosSoloLogService - error streaming log for job=tmp-20170117-f7c0048_registry.spotify.net_spotify_cassandra_latest:88037fe:3840e30a6f3053207837a227cc5d34fb872d0650, container=0c4cd5794f38190afb906f96cb7a3846f96faf1630e1044e22700bdbd69d1268
java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
	at com.spotify.helios.testing.LoggingLogStreamFollower.followLog(LoggingLogStreamFollower.java:83)
	at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:150)
	at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.RuntimeException: java.net.SocketException: Socket closed
		at com.google.common.base.Throwables.propagate(Throwables.java:160)
		at com.spotify.docker.client.LogStream.close(LogStream.java:75)
		at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:151)
		... 7 common frames omitted
	Caused by: java.net.SocketException: Socket closed
		at java.net.SocketInputStream.read(SocketInputStream.java:203)
		at java.net.SocketInputStream.read(SocketInputStream.java:141)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
		at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
		at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
		at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
		at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at java.io.FilterInputStream.read(FilterInputStream.java:133)
		at java.io.FilterInputStream.read(FilterInputStream.java:107)
		at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:96)
		at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:297)
		at com.google.common.io.ByteStreams.copy(ByteStreams.java:110)
		at com.spotify.docker.client.LogReader.close(LogReader.java:96)
		at com.spotify.docker.client.LogStream.close(LogStream.java:73)
		... 8 common frames omitted
```

not sure if the suppressed exception is relevant or a cause, or just a coincidence

**Comment by mattnworb** [comment]
reported by @odsod

**Comment by dflemstr** [comment]
The suppressed exception should be unrelated, it's what happens if you throw an exception in the implicit finally block of a try-with-resources statement.

It would be good to have a failing test case for this problem, now there is no way of telling what caused this. Maybe @odsod could clarify what happened?

**Comment by mattnworb** [comment]
from the same Jenkins run that produced the above stacktrace:

```
java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
	at com.spotify.helios.testing.LoggingLogStreamFollower.followLog(LoggingLogStreamFollower.java:83)
	at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:150)
	at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.RuntimeException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
		at com.google.common.base.Throwables.propagate(Throwables.java:160)
		at com.spotify.docker.client.LogStream.close(LogStream.java:75)
		at com.spotify.helios.testing.HeliosSoloLogService$LogFollowJob.call(HeliosSoloLogService.java:151)
		... 7 common frames omitted
	Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
		at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:268)
		at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
		at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
		at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at java.io.FilterInputStream.read(FilterInputStream.java:133)
		at java.io.FilterInputStream.read(FilterInputStream.java:107)
		at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:96)
		at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:297)
		at com.google.common.io.ByteStreams.copy(ByteStreams.java:110)
		at com.spotify.docker.client.LogReader.close(LogReader.java:96)
		at com.spotify.docker.client.LogStream.close(LogStream.java:73)
		... 8 common frames omitted
```

I missed when making the issue that the suppressed exception was different each time it occurred

**Comment by dflemstr** [comment]
I think the problem isn't related to the stack trace; the underlying cause here is that the log HTTP stream was terminated prematurely and this simply reports that.  The question is why that happened: did something asynchronously stop the container? Did the docker daemon crash? etc
