### ISSUE TITLE
NPE when endpoint host misbehaves (helios status command)

### ISSUE THREAD

**Issue by perfa** [spotify/helios#333]
```
mango@fruitbox:(master u=):~/workshop_test$ helios status -z http://some.fqdn.net:2375 -vvvv
14:47:55.214 DEBUG HeliosClient: endpoint uris are [http://some.fqdn.net:2375]
14:47:55.217 DEBUG HeliosClient: connecting to http://some.fqdn.net:2375/jobs?user=mango
14:47:55.284 TRACE HeliosClient: req: GET http://some.fqdn.net:2375/jobs?user=mango 1 Helios-Version=[0.8.130] 0 ""
14:47:55.479 TRACE HeliosClient: rep: GET http://some.fqdn.net:2375/jobs?user=mango 404 19 404 page not found
 gzip:false
14:47:55.479 DEBUG HeliosClient: Server didn't return a version header!
java.lang.NullPointerException
    at com.spotify.helios.cli.command.JobStatusCommand.run(JobStatusCommand.java:95)
    at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:122)
    at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:89)
    at com.spotify.helios.cli.CliMain.run(CliMain.java:79)
    at com.spotify.helios.cli.CliMain.main(CliMain.java:57)
```

**Comment by davidxia** [comment]
@perfa Thanks for this. Were you also running helios version 0.8.130 on some.fqdn.net? Do you have logs from that host or any idea of what the response was that caused this?

**Comment by noaresare** [comment]
This can be reproduced with latest master with any master URL that doesn't return the expected data. For example: `helios status -z http://xkcd.com:80/foo -vvvv`
