### ISSUE TITLE
Concurrency issue: NoNodeException when listing job while another job is being removed

### ISSUE THREAD

**Issue by jypma** [spotify/helios#459]
In an attempt to speed up our communication with helios master, I tried undeploying the ~20 jobs that make up our stack in parallel. This works fine most of the time, but sometimes it seems that a request to 
```GET /jobs?q=backend_service1:jyp&user=jan]```
will fail with `KeeperErrorCode = NoNode for /config/jobs/riak1:jyp:7adc0[...]` if another concurrent request 
```DELETE /jobs/riak1:jyp:7adc0[...]?token=&user=jan]```
is currently messing with certain zookeeper nodes that `/jobs` tries to list. Partial log and exception follows:
```
1220358860 [dw-18377 - GET /jobs?q=backend_service1:jyp&user=jan] DEBUG c.s.h.master.ZooKeeperMasterModel - getting jobs 
1220358861 [dw-18362] DEBUG c.s.h.m.http.VersionResponseFilter - version 0.8.245 state EQUAL 
1220358861 [dw-18362 - DELETE /jobs/riak1:jyp:7adc06e77436eaa0c81219c561196437c7a5d7b1?token=&user=jan] INFO  c.s.h.master.ZooKeeperMasterModel - removing job: id=riak1:jyp:7adc06e77436eaa0c81219c561196437c7a5d7b1 
1220358868 [dw-18377 - GET /jobs?q=backend_service1:jyp&user=jan] ERROR i.d.j.errors.LoggingExceptionMapper - Error handling a request: 74a59fb06940b030 
com.spotify.helios.common.HeliosRuntimeException: getting jobs failed
        at com.spotify.helios.master.ZooKeeperMasterModel.getJobs(ZooKeeperMasterModel.java:403) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at com.spotify.helios.master.resources.JobsResource.list(JobsResource.java:96) ~[helios-services-0.8.245-shaded.jar:0.8.245]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /config/jobs/riak1:jyp:7adc06e77436eaa0c81219c561196437c7a5d7b1
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:115) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1611) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:302) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:291) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:288) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:279) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:41) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at com.spotify.helios.servicescommon.coordination.DefaultZooKeeperClient.getData(DefaultZooKeeperClient.java:137) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at com.spotify.helios.servicescommon.coordination.ReportingZooKeeperClient.getData(ReportingZooKeeperClient.java:78) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        at com.spotify.helios.master.ZooKeeperMasterModel.getJobs(ZooKeeperMasterModel.java:397) ~[helios-services-0.8.245-shaded.jar:0.8.245]
        ... 58 common frames omitted
```

**Comment by jypma** [comment]
Using helios 0.8.245.

**Comment by rohansingh** [comment]
Thanks. I noticed this in our logs too but hadn't had time to dig deeper. I'll try to look into it now.

**Comment by davidxia** [comment]
@jypma Closing as this issue is fixed by https://github.com/spotify/helios/pull/461.
