### ISSUE TITLE
NPE when running deployment-group-status 

### ISSUE THREAD

**Issue by goldfishy** [spotify/helios#647]
**Running:**
helios -z http://master:5801 deployment-group-status my-group-name -v

**Results in:**
```
java.lang.NullPointerException
	at com.spotify.helios.cli.command.DeploymentGroupStatusCommand.run0(DeploymentGroupStatusCommand.java:96)
	at com.spotify.helios.cli.command.DeploymentGroupStatusCommand.run(DeploymentGroupStatusCommand.java:74)
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:131)
	at com.spotify.helios.cli.command.ControlCommand.run(ControlCommand.java:94)
	at com.spotify.helios.cli.CliMain.run(CliMain.java:79)
	at com.spotify.helios.cli.CliMain.main(CliMain.java:57)
```
**And sometime unpredictably we also get:**
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.spotify.helios.common.descriptors.DeploymentGroupStatus$State from String value 'PLANNING_ROLLOUT': value not one of declared Enum instance names: [ROLLING_OUT, FAILED, DONE]
at [Source: [B@6ebc05a6; line: 1, column: 611]
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
    at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:797)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:127)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:81)
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:17)
```

**Comment by davidxia** [comment]
@goldfishy Do you have data in your ZK cluster that was created from a previous version of helios? Sometimes old data is serialized in a way that newer versions of helios can't parse. Try `helios remove-deployment-group`?

**Comment by davidxia** [comment]
@goldfishy Have you seen this error again? If not, could I close this?
